name: my_postgres
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
  - {name: my-postgres, version: latest}

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: my_pg_node
    instances: 1
    azs: [z1]
    jobs:
    - name: my_pg_server
      release: my-postgres
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    networks:
      - name: default


